# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

reviews:
  # "строгий" режим у CodeRabbit = assertive
  profile: assertive           # допустимі значення: chill | assertive

  high_level_summary: true
  review_status: true

  auto_review:
    enabled: true
    auto_incremental_review: true   # ревʼю кожного пуша в PR
    drafts: false

    # УВАГА: вкажи тут, куди ти реально робиш PR
    base_branches:
      - "^develop$"                 # ревʼю всіх PR, де base = develop

    ignore_title_keywords:
      - "WIP"
      - "DRAFT"
    ignore_usernames:
      - "dependabot"
      - "renovate-bot"

  # Загальні інструкції
  instructions: |
    You are reviewing a monorepo with:
    - Next.js app in the "client" folder
    - NestJS API in the "server" folder

    General:
    - Be strict about code quality, readability and maintainability.
    - Suggest refactoring when code is too complex, duplicated or violates SOLID principles.
    - Prefer small, focused functions and clear separation of concerns.
    - Point out potential security, performance and reliability issues with clear, actionable suggestions.
    - Make sure configuration and secrets are not hard-coded.

    For both client and server:
    - Check for dead code, unused imports, and overly complex conditionals.
    - Encourage consistent error handling and logging patterns.

# Що саме ревʼюємо
path_filters:
  - "client/**"
  - "server/**"
  - "!**/*.md"
  - "!**/dist/**"
  - "!**/build/**"

# Спеціальні інструкції для client (Next.js)
path_instructions:
  - path: "client/**"
    instructions: |
      This is a Next.js application.
      - Check React component structure, props, and state management.
      - Prefer small, reusable components over large ones.
      - Point out unnecessary re-renders and obvious performance issues.
      - Verify correct usage of Next.js features (routing, data fetching, app/router usage).
      - Encourage accessibility (a11y), semantic HTML, and clear UX.

  # Спеціальні інструкції для server (NestJS)
  - path: "server/**"
    instructions: |
      This is a NestJS backend application.
      - Enforce NestJS best practices: modules, controllers, services, providers separation.
      - Suggest splitting or refactoring services/controllers that are too large or do too many things.
      - Encourage use of DTOs, validation pipes, and proper error handling.
      - Check for security issues: validation, guards, direct use of user input in queries, etc.
      - Use dependency injection properly and avoid tight coupling.
      - Suggest extracting shared logic into reusable providers/helpers where appropriate.

tools:
  eslint:
    enabled: true
  gitleaks:
    enabled: true
