version: "3.8"

services:
  server:
    container_name: housescrm-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    working_dir: /app
    volumes:
      - ./server:/app
    command: npm run start:prod  
    restart: unless-stopped
    environment:
      - NODE_ENV=production
