version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app

  # client:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app
  #   depends_on:
  #     - server
