import { HouseChartDataItem } from '@/types/core/chart-pie-item';

export const chartHouseData: HouseChartDataItem[] = [
  {
    apartmentName: 'вул. Соборна 338',
    apartmentTotalRevenue: 2100000,
    percentage: 19.95,
    fill: 'var(--chart-pie-1)',
    id: '1',
  },
  {
    apartmentName: 'вул. Київська 12Б',
    apartmentTotalRevenue: 420000,
    percentage: 3.99,
    fill: 'var(--chart-pie-2)',
    id: '2',
  },
  {
    apartmentName: 'вул. Грушевського 7',
    apartmentTotalRevenue: 580000,
    percentage: 5.51,
    fill: 'var(--chart-pie-3)',
    id: '3',
  },
  {
    apartmentName: 'вул. Степана Бандери 8',
    apartmentTotalRevenue: 1150000,
    percentage: 10.93,
    fill: 'var(--chart-pie-4)',
    id: '4',
  },
  {
    apartmentName: 'вул. Кулика і Гудачека 23',
    apartmentTotalRevenue: 360000,
    percentage: 3.42,
    fill: 'var(--chart-pie-5)',
    id: '5',
  },
  {
    apartmentName: 'вул. Вербова 24',
    apartmentTotalRevenue: 640000,
    percentage: 6.08,
    fill: 'var(--chart-pie-6)',
    id: '6',
  },
  {
    apartmentName: 'вул. Млинівська 10',
    apartmentTotalRevenue: 290000,
    percentage: 2.76,
    fill: 'var(--chart-pie-7)',
    id: '7',
  },
  {
    apartmentName: 'вул. Данила Галицького 35',
    apartmentTotalRevenue: 870000,
    percentage: 8.27,
    fill: 'var(--chart-pie-8)',
    id: '8',
  },
  {
    apartmentName: 'вул. Олександра Олеся 3',
    apartmentTotalRevenue: 330000,
    percentage: 3.14,
    fill: 'var(--chart-pie-9)',
    id: '9',
  },
  {
    apartmentName: 'вул. Набережна 25А',
    apartmentTotalRevenue: 960000,
    percentage: 9.13,
    fill: 'var(--chart-pie-10)',
    id: '10',
  },
  {
    apartmentName: 'вул. Костромська 77',
    apartmentTotalRevenue: 410000,
    percentage: 3.9,
    fill: 'var(--chart-pie-11)',
    id: '11',
  },
  {
    apartmentName: 'вул. Академіка Грушевського 42',
    apartmentTotalRevenue: 720000,
    percentage: 6.85,
    fill: 'var(--chart-pie-12)',
    id: '12',
  },
  {
    apartmentName: 'вул. Орлова 9',
    apartmentTotalRevenue: 250000,
    percentage: 2.38,
    fill: 'var(--chart-pie-13)',
    id: '13',
  },
  {
    apartmentName: 'вул. Чорновола 101',
    apartmentTotalRevenue: 1300000,
    percentage: 12.35,
    fill: 'var(--chart-pie-14)',
    id: '14',
  },
  {
    apartmentName: 'вул. Міцкевича 16',
    apartmentTotalRevenue: 540000,
    percentage: 5.13,
    fill: 'var(--chart-pie-15)',
    id: '15',
  },
];
